export const FontFamilies = [
  'Unset',

  'Agency FB',
  'Albertina',
  'Antiqua',
  'Architect',
  'Arial',
  'BankFuturistic',
  'BankGothic',
  'Blackletter',
  'Blagovest',
  'Calibri',
  'Comic Sans MS',
  'Consolas',
  'Courier',
  'Cursive',
  'Decorative',
  'Fantasy',
  'Fraktur',
  'Frosty',
  'Garamond',
  'Georgia',
  'Helvetica',
  'Houschka Rounded Alt',
  'Impact',
  'Lora-BoldItalic',
  'Lora-Italic',
  'Lora-Regular',
  'Minion',
  'Modern',
  'Monospace',
  'Open Sans',
  'Oswald-Bold',
  'Oswald-BoldItalic',
  'Oswald-Demi-BoldItalic',
  'Oswald-DemiBold',
  'Oswald-Extra-LightItalic',
  'Oswald-ExtraLight',
  'Oswald-Heavy',
  'Oswald-HeavyItalic',
  'Oswald-Light',
  'Oswald-LightItalic',
  'Oswald-Medium',
  'Oswald-MediumItalic',
  'Oswald-Regular',
  'Oswald-RegularItalic',
  'Oswald-Stencil',
  'Palatino',
  'Perpetua',
  'Roboto-Regular',
  'RobotoCondensed-Regular',
  'Roman',
  'Sans-serif',
  'Script',
  'Serif',
  'Swiss',
  'ScoutCond-Regular',
  'ScoutCond-Light',
  'ScoutCond-ExtraLight',
  'ScoutCond-Bold',
  'ScoutCond-Thin',
  'ScoutCond-Black',
  'Scout-Regular',
  'Scout-RegularlItalic',
  'Scout-Light',
  'Scout-Bold',
  'Scout-BoldItalic',
  'Tahoma',
  'Times New Roman ',
  'Times',
  'Tw Cen MT',
  'Verdana',
  'Lora-Bold',
];

export const FontStyles = ['Unset', 'Italic', 'Normal'];

export const FontWeights = [
  'Unset',
  'normal',
  'bold',
  'bolder',
  'lighter',
  'initial',
];

export const Alignments = ['center', 'left', 'right'];

export const BorderSizes = ['0', '1', '2', '3', '4', '5'];
