export const CommonMessages = {
  ConfirmDeleteMessage: 'Are you sure, you want to delete this item?',
  ConfirmDuplicateMessage: 'Are you sure, you want to create copy of this item?',
  FileTypeErrorMessage: 'Please select valid file type.',
  ImageFileSizeErrorMessage: 'Please select file less than 4 mb.',
  VideoFileSizeErrorMessage: 'Please select file less than 50 mb',
  FeatureComingSoonMessage: 'This feature is coming soon',
  NotesNotAvailableMessage: 'Commenting on ticket is not allowed.',
  SMSNotAvailableMessage: 'Sending SMS message is not allowed.',
  SMSNotProvided: 'SMS number is not provided',
  SMSNotLinked: 'SMS number is not linked in location.',
  CancelRequestByCustomerConfimationMessage: 'Are you sure you want to leave the line?',
  ConfirmReposition: 'Are you sure you want to send this visitor back into the queue?',
  ConfirmRunningLateOnMobile: 'Are you sure you need more time?',
  SelectAtLeastAGroupToAssign: 'Please select at least one visitor tag.',
  ConfirmationGroupDeletion: 'Are you sure you want to delete this visitor tag?',
  ConfirmationAppointmentDeletion: 'Are you sure you want to delete this appointment?',
  PleaseAnswerAllQuestionAddVisitor: 'Must fill out all required fields.',
  SMSNumberNotExists: 'SMS number is not available for visitor.',
  AgentTemplateUsedMessage: 'Agent template is used in agent.',
  FeatureNotAvailableForLavi: 'This feature is currently not available for lavi User.',
  VisitorAdded: `Visitor added successfully.`,
  VisitorTransferred: `Visitor transferred successfully.`,
  VisitorUpdated: `Visitor updated successfully.`,
  SchedulerTemplateNotConnected: 'Scheduler Template is not connected.',
  ConfirmDeleteCustomerMessage: 'Are you sure you want to remove this ticket?',
  NextUpIsEmpty:'No visitors present to be called.',
  NameIsNotAllowedMessage : 'This name is not allowed to set.',
  EndOfDayConfirmationMessage : 'Are you sure you would like to clear the Queue of any remaining tickets, reset all ticket numbers, and set any remaining logged-in staff to Inactive?'
};
