import { ISideBarItems } from 'src/app/features/auth/side-bar-item.interface';
import { RoleActionsPageNameEnum } from '../enums/role-actions.enum';

export const ManageSideBarItems: ISideBarItems[] = [
  {
    id: 'settingNav',
    text: 'Settings',
    icon: 'nav-setting-icon',
    path: '#',
    level: 1,
    name: '',
    parentId: '',
    canCompanyUserAccess: true,
    isParentSelected: true,
  },
  {
    id: 'companyNav',
    text: 'Company',
    icon: '',
    path: '//manage//company-configuration',
    level: 2,
    name: RoleActionsPageNameEnum.CompanyConfiguration,
    canCompanyUserAccess: true,
    parentId: 'settingNav',
  },
  {
    id: 'locationsNav',
    text: 'Locations',
    icon: '',
    path: '//manage//branches',
    level: 2,
    name: RoleActionsPageNameEnum.Branches,
    canCompanyUserAccess: true,
    parentId: 'settingNav',
  },
  {
    id: 'workFlowsNav',
    text: 'Workflows',
    icon: '',
    path: '//manage//work-flow',
    level: 2,
    name: RoleActionsPageNameEnum.WorkflowTemplates,
    canCompanyUserAccess: true,
    parentId: 'settingNav',
  },
  {
    id: 'hoursOfOperationsNav',
    text: 'Hours of Operations',
    icon: '',
    path: '//manage//hours-of-operations',
    level: 2,
    name: RoleActionsPageNameEnum.HOOTemplates,
    canCompanyUserAccess: true,
    parentId: 'settingNav',
  },
  {
    id: 'agentTemplatesNav',
    text: 'Queue Views',
    icon: '',
    path: '//manage//agent-Template',
    level: 2,
    name: RoleActionsPageNameEnum.AgentTemplates,
    canCompanyUserAccess: true,
    parentId: 'settingNav',
  },
  {
    id: 'designNav',
    text: 'Design',
    icon: 'nav-design-icon',
    path: '#',
    canCompanyUserAccess: true,
    name: '',
    level: 1,
    parentId: '',
  },
  {
    id: 'kioskTemplatesNav',
    text: 'Kiosk Templates',
    icon: '',
    path: '//manage//kiosk-template',
    level: 2,
    name: RoleActionsPageNameEnum.KioskTemplates,
    canCompanyUserAccess: true,
    parentId: 'designNav',
  },
  {
    id: 'monitorTemplatesNav',
    text: 'Monitor Templates',
    icon: '',
    path: '//manage//monitor-template',
    level: 2,
    name: RoleActionsPageNameEnum.MonitorTemplates,
    canCompanyUserAccess: true,
    parentId: 'designNav',
  },
  {
    id: 'appointmentsNav',
    text: 'Scheduler Interfaces',
    icon: '',
    path: '//manage//appointment-scheduler',
    level: 2,
    name: RoleActionsPageNameEnum.SchedulerTemplates,
    canCompanyUserAccess: true,
    parentId: 'designNav',
  },
  {
    id: 'mobileInterfacesNav',
    text: 'Mobile Interfaces',
    icon: '',
    path: '//manage//mobile-interfaces',
    level: 3,
    name: RoleActionsPageNameEnum.MobileTemplates, // need to add
    canCompanyUserAccess: true,
    parentId: 'designNav',
  },
  {
    id: 'homeInterfacesNav',
    text: 'Home Interfaces',
    icon: '',
    path: '//manage//home-interfaces',
    level: 3,
    name: RoleActionsPageNameEnum.HomeInterfaces, // need to add
    canCompanyUserAccess: true,
    parentId: 'designNav',
  },
  {
    id: 'adminNav',
    text: 'Admin',
    icon: 'nav-admin-icon',
    path: '//manage//appointment-scheduler',
    canCompanyUserAccess: false,
    name: '',
    level: 1,
    parentId: '',
  },
  {
    id: 'allCompaniesNav',
    text: 'All Companies',
    icon: '',
    path: '//manage//companies',
    level: 2,
    name: RoleActionsPageNameEnum.AllCompanies,
    canCompanyUserAccess: false,
    parentId: 'adminNav',
  },
  {
    id: 'allUsersNav',
    text: 'All Users',
    icon: '',
    path: '//manage//all-users',
    level: 2,
    name: RoleActionsPageNameEnum.AllUsers,
    canCompanyUserAccess: false,
    parentId: 'adminNav',
  },
  {
    id: 'permissionNav',
    text: 'Permissions',
    icon: 'nav-permissions-icon',
    path: '#',
    canCompanyUserAccess: true,
    name: '',
    level: 1,
    parentId: '',
  },
  {
    id: 'usersNav',
    text: 'Users',
    icon: '',
    path: '//manage//user',
    level: 2,
    canCompanyUserAccess: true,
    name: RoleActionsPageNameEnum.Users,
    parentId: 'permissionNav',
  },
  {
    id: 'userRolesNav',
    text: 'Roles',
    icon: '',
    path: '//manage//user-role',
    level: 2,
    canCompanyUserAccess: true,
    name: RoleActionsPageNameEnum.UserRoles,
    parentId: 'permissionNav',
  },
];
